graph LR
A["Improve F# ecosystem"]
B["Contribute to F# ecosystem"]
C["Level-up F# knowledge"]
D["Increase daily productivity"]

A --> B
B --> C
B --> D
style A fill:#2d3436,stroke:#F8F9FA,color:#FFF
style B fill:#2d3436,stroke:#F8F9FA,color:#FFF
style C fill:#2d3436,stroke:#F8F9FA,color:#FFF
style D fill:#2d3436,stroke:#F8F9FA,color:#FFF