graph LR
    A["Make money with F#"]
    B["Invest money in F# eco system"]
    A --> B
    B --> A
    style A fill:#2d3436,stroke:#F8F9FA,color:#FFF
    style B fill:#2d3436,stroke:#F8F9FA,color:#FFF